train_batch_size: 64
train_epochs: 20

shuffle: false
eval_batch_size: 8
eval_strategy: epoch

# gradient_clip_val: 1.0

project: latent-dialog-v2
run_name: roberta-small
num_sanity_val_steps: 1

limit_train_batches: 200
limit_val_batches: 1