train_batch_size: 32
train_steps: 1000000
# accelerator: cpu # cpu for test, gpu default

shuffle: false
eval_batch_size: 8
eval_strategy: steps

optimus_checkout_step: 25000
val_check_interval: 50000
project: optimus
run_name: v2-mini-vae
num_sanity_val_steps: 1