defaults:
- optimizer: adam
- logger: wandb
- dataset: latent-dialog
- model: latent-dialog-roberta-small
- trainer: latent-dialog
- _self_

# trainer:
#   run_name: tiny-opt44M

optimizer:
  learning_rate: 5e-5