defaults:
- optimizer: adam-sgpt
- logger: wandb
- dataset: sgpt-conv
- model: sgpt-tiny
- trainer: sgpt-tiny
- _self_

model:
  max_seq_len: 32
trainer:
  run_name: tiny-opt44M

optimizer:
  learning_rate: 1e-3
