train:
  - heegyu/kowiki-sentences
  - heegyu/namuwiki-sentences
  - heegyu/aihub_web_2021
  - heegyu/aihub_spoken_2021
  - heegyu/aihub_daily_conv_2022_sentences
  
test:
  path: "csv"
  data_files: ../../../data/optimus_v2_val.csv
  split: "train"