train:
  - heegyu/kowiki-sentences
  - heegyu/namuwiki-sentences
  - heegyu/aihub_web_2021
  - heegyu/aihub_spoken_2021
  - heegyu/aihub_daily_conv_2022_sentences
train_weights: [10, 10, 10, 10, 3]
  
test:
  - "heegyu/vae_eval"