train:
  - heegyu/kowiki-sentences
  - heegyu/namuwiki-sentences
  - heegyu/aihub_web_2021
  - heegyu/aihub_spoken_2021
  
test:
  path: "csv"
  data_files: ../../../data/optimus_v2_val.csv
  split: "train"